---
app_repo: "https://github.com/pravinmishraaws/theepicbook"
app_dest: "/home/azureuser/theepicbook"
app_user: "azureuser"

nginx_site_name: "epicbook"

app_port: 8080

db_host: "bookstore.mysql.database.azure.com"
db_user: "adminuser"
db_name: "bookstore"
db_password: "{{ vault_db_password }}"

ansible_python_interpreter: /usr/bin/python3
