---
app_repo: "https://github.com/pravinmishraaws/theepicbook"
app_dest: "/home/ubuntu/theepicbook"
app_user: "ubuntu"

nginx_site_name: "epicbook"

app_port: 8080

db_host: "terraform-20260403071536148600000003.czau4uacam1c.eu-north-1.rds.amazonaws.com"
db_user: "admin"
db_name: "bookstore"
db_password: "{{ vault_db_password }}"

ansible_python_interpreter: /usr/bin/python3
